name: vocabualize
description: Capture vocabularies around you.



publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.3.0"



dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  cached_network_image: ^3.2.2
  image_picker: ^0.8.7
  path_provider: ^2.0.13
  shared_preferences: ^2.0.18
  http: ^0.13.5
  provider: ^6.0.3
  intl: ^0.17.0
  permission_handler: ^10.0.2
  url_launcher: ^6.1.10

  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  snapping_sheet: ^3.1.0

  speech_to_text: ^6.1.1
  text_to_speech: ^0.2.3
  translator: ^0.1.7

  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4

  # own packages
  log:
    path: ./packages/log
  teleport:
    path: ./packages/teleport
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icon/
    - assets/images/mascot/

flutter_intl:
  enabled: true
  class_name: AppLocalizations