name: vocabualize
description: Capture vocabularies around you.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  # functionality
  async: ^2.11.0
  cached_network_image: ^3.4.0
  device_info_plus: ^10.1.1
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^17.2.1+2
  flutter_secure_storage: ^9.2.2
  flutter_timezone: ^2.1.0
  galli_text_to_speech: ^0.0.1
  get_it: ^7.7.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  path_provider: ^2.0.13
  permission_handler: ^11.0.0
  pocketbase: ^0.18.1
  provider: ^6.0.3
  rxdart: ^0.28.0
  shared_preferences: ^2.0.18
  speech_to_text: ^6.6.0
  translator_plus: ^1.0.1
  url_launcher: ^6.1.10
  uuid: ^4.4.2

  # styling
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.2
  google_fonts: ^6.2.1
  snapping_sheet: ^3.1.0

  # firebase
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_cached_image: ^0.6.1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.2

  # own packages
  log:
    path: ./packages/log


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icon/
    - assets/images/mascot/


flutter_intl:
  enabled: true
  class_name: AppLocalizations


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon_transparent.png"
  adaptive_icon_background: "#22A2FF"
  adaptive_icon_foreground: "assets/images/icon/icon_transparent.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true


flutter_native_splash:
  android: true
  ios: true
  color: "#22A2FF"
  image: "assets/images/icon/icon_transparent.png"
  android_12:
    #image: "assets/images/icon/icon_transparent.png"
    color: "#22A2FF"
