// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSDE2wWo49JZ-AzmQYah8hxYW6Nob4Dqg',
    appId: '1:351179268452:web:b216db614a21f40a53da71',
    messagingSenderId: '351179268452',
    projectId: 'vocabualize',
    authDomain: 'vocabualize.firebaseapp.com',
    storageBucket: 'vocabualize.appspot.com',
    measurementId: 'G-40ZD85ZCTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6LvQq5kLoGyt4ZhmcKNuT-E9s4mz6JdM',
    appId: '1:351179268452:android:043979c2e45f1ed953da71',
    messagingSenderId: '351179268452',
    projectId: 'vocabualize',
    storageBucket: 'vocabualize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQisQyRbFGAXPSExIU1RV2UFRM5GbIDxQ',
    appId: '1:351179268452:ios:817dd5fdc80f2f1253da71',
    messagingSenderId: '351179268452',
    projectId: 'vocabualize',
    storageBucket: 'vocabualize.appspot.com',
    iosClientId: '351179268452-0rei9k77ac3plod5ca97v55o285suvf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocabualize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQisQyRbFGAXPSExIU1RV2UFRM5GbIDxQ',
    appId: '1:351179268452:ios:817dd5fdc80f2f1253da71',
    messagingSenderId: '351179268452',
    projectId: 'vocabualize',
    storageBucket: 'vocabualize.appspot.com',
    iosClientId: '351179268452-0rei9k77ac3plod5ca97v55o285suvf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocabualize',
  );
}
